version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TINA_PUBLIC_IS_LOCAL=true
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=tinacms
      - NEXTAUTH_URL=http://localhost:4321
      - NEXTAUTH_SECRET=your-development-secret
      - TINA_USERNAME=admin
      - TINA_PASSWORD=password
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: