[build]
  command = "pnpm install && pnpm build"
  publish = "dist"
  environment = { NODE_VERSION = "18" } # Match your local version

[context.production.environment]
  NEXT_PUBLIC_TINA_CLIENT_ID = "$TINA_CLIENT_ID"
  TINA_TOKEN = "$TINA_TOKEN"