[build]
  command = "pnpm install && pnpm generate:types && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # Must be 16 or 18
  PNPM_VERSION = "10"   # Match your local version